// This file was generated by lezer-generator. You probably shouldn't edit it.
export const LineComment = 1,
  File = 2,
  Fork = 3,
  Label = 4,
  Join = 5,
  Assign = 6,
  Digit = 7,
  Call = 8,
  Def = 9;
